---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: LinkCheck
        uses: Consensys-Incorporated/github-actions/docs-link-check@89c262a30cae735be99dc776f9556b796fb456ca # v1.0.0
        with:
          CONFIG_FILE: .linkspector.yml
