---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: LinkCheck
        uses: Consensys-Incorporated/github-actions/docs-link-check@89c262a30cae735be99dc776f9556b796fb456ca # v1.0.0
        with:
          CONFIG_FILE: .linkspector.yml
