---
name: Trivy

on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    name: Run trivy scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Trivy
        uses: Consensys-Incorporated/github-actions/trivy@89c262a30cae735be99dc776f9556b796fb456ca # v1.0.0
